/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'

/* Instruments */
// import { incrementAsync } from './thunks'

const initialState: GlobalSliceState = {}

export const globalSlice = createSlice({
  name: 'global',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    showIChat: (state) => {
      state.showIChat = true
    },
    hideIChat: (state) => {
      state.showIChat = false
    },
    setXingyun: (state, action: PayloadAction<string | undefined>) => {
      state.xingyun = action.payload
    },
    showDownloadPopup: (state) => {
      state.showDownload = true
    },
    hideDownloadPopup: (state) => {
      state.showDownload = false
    },
    hideFooterApp: (state) => {
      state.hideAppDl = true
    },
    showFooterApp: (state) => {
      state.hideAppDl = false
    },
    setIsMobile: (state, action: PayloadAction<boolean>) => {
      state.isMobile = action.payload
    },
    enableInitialMobile: (state) => {
      state.isInitialMobile = true
    },
    enableTracking: (state) => {
      state.tracking = true
    },
    disableTracking: (state) => {
      state.tracking = false
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading'
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle'
  //       state.value += action.payload
  //     })
  // },
})

export const {
  showIChat,
  hideIChat,
  setXingyun,
  showDownloadPopup,
  hideDownloadPopup,
  hideFooterApp,
  showFooterApp,
  setIsMobile,
  enableInitialMobile,
  enableTracking,
  disableTracking,
 } = globalSlice.actions

/* Types */
export interface GlobalSliceState {
  /**
   * 显示iChat弹层。
   */
  showIChat?: boolean
  /**
   * 星云展厅小程序码URL。
   */
  xingyun?: string
  /**
   * 显示下载提示（用默认浏览器打开）。
   */
  showDownload?: boolean
  /**
   * 隐藏底部APP下载。
   */
  hideAppDl?: boolean
  isMobile?: boolean
  isInitialMobile?: boolean
  /**
   * 监测代码追踪。
   */
  tracking?: boolean
}
